name: ShellCheck

on:
  push:
    paths:
      - '**.sh'
      - '**.bash'
      - '**.zsh'
  pull_request:
    paths:
      - '**.sh'
      - '**.bash'
      - '**.zsh'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ShellCheck
        run: sudo apt-get install -y shellcheck

      - name: Run ShellCheck
        run: |
          find . -type f \( -name "*.sh" -o -name "*.bash" -o -name "*.zsh" \) -print0 | xargs -0 shellcheck
